version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.49"
    BUCKET_NAME: "open-security-summit.com-cdn"
    DISTRIBUTION_ID: "E22WEBPD6529KA"
    AWS_DEFAULT_REGION: "eu-west-2"

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR && git submodule init && git submodule update
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --sse "AES256" public/ s3://${BUCKET_NAME}/2019/
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: 'public'

